package main;

import java.io.File;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import model.MenuController;
import model.Shoe;
import model.Shoe.Side;
import model.TimeController;
import view.mainwindow.MainView;
import view.otherwindow.ErrorWindow;


/**
 * Main class of the Tactile Shoe Player.<br>
 * This class has to instanciate the model and the view and to close the 
 * software properly.
 * @author Loïc David
 */
public class Main extends Application{
    
    TimeController timeController;
    Shoe shoeModelRight;
    Shoe shoeModelLeft;
    
    /**
     * Method used to start the software.<br>
     * Instanciate the model and the view.
     * @param primaryStage The Window, automaticaly generated by the launch
     * method.
     * @throws Exception If something goes wrong.
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        
        try {
            // Model.
            shoeModelRight = new Shoe(Side.RIGHT);
            shoeModelLeft = new Shoe(Side.LEFT);
            timeController = new TimeController(shoeModelLeft, shoeModelRight);
            MenuController menuController = new MenuController(timeController, shoeModelLeft, shoeModelRight);

            // View.
            MainView mainView = new MainView(menuController, timeController, shoeModelLeft, shoeModelRight);

            // Initialize window.
            String path = new File(".//.//ressources//logo.png").toURI().toString();
            Image logoImage = new Image(path);
            Scene scene = new Scene(mainView);
            primaryStage.setTitle("Tactile Shoe Player");
            primaryStage.getIcons().add(logoImage);
            primaryStage.setScene(scene);
            primaryStage.setResizable(false);
            primaryStage.sizeToScene();
            primaryStage.show();
        } catch (Exception e) {
            (new ErrorWindow("Error initializing software!\nPlease, check the setting files.")).show();
        }
        
    }
    
    /**
     * Method used to close the software.<br>
     * Close all the parts of the software to be sure it will end properly.
     * @throws Exception If something goes wrong.
     */
    @Override
    public void stop() throws Exception {
        timeController.readCSVProperty().setValue(false);
        shoeModelLeft.getSerialReader().stopRead();
        shoeModelRight.getSerialReader().stopRead();
        shoeModelLeft.getSerialReader().closePort();
        shoeModelRight.getSerialReader().closePort();
        super.stop();
    }
    
    /**
     * Launch the software.
     * @param args This software doesn't need any argument.
     */
    public static void main(String[] args) {
        launch(args);
    }
    
}